### ISSUE TITLE
assign Domain Leaders - Due 3/7

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#454] opened 2020-05-04 19:16 UTC
## User story /  Background

During today's Sprint Planning meeting, we discussed for the Deep Grooming session next Monday 5/11 to leverage Domain Owners so those owners can validate that each issue has the appropriate acceptance criteria and add any issues to the domain that might be missing. 

Notes: Issues may cross multiple Domains

## Acceptance Criteria

- [ ] @afeld create Domain Leaders

**Comment by afeld** [comment] 2020-05-04 19:35
Duplicate of https://github.com/18F/tts-tech-portfolio/issues/453.

**Closed by afeld** 2020-05-04 19:35 UTC
