### ISSUE TITLE
Remove TTS Inspector notifications from any `*-public` channels and post to next in line

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#1099] opened 2020-12-14 17:45 UTC
https://gsa-tts.slack.com/archives/C02KXM98G/p1607967313145800

**Comment by afeld** [comment] 2020-12-14 20:49
Duplicate of https://github.com/18F/tts-tech-portfolio/issues/948.

**Closed by afeld** 2020-12-14 20:49 UTC
