### ISSUE TITLE
*REMINDER* Pegasys Transactions Reports Completion Due for John Jediny

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#1343] opened 2021-05-24 15:21 UTC
## Implementation Steps
- [ ] Resolve 10 remaining transactions

## Acceptance Criteria
- [ ] All past transactions reconciled

**Comment by afeld** [comment] 2021-05-24 15:22
Duplicate of https://github.com/18F/tts-tech-portfolio/issues/1341.

**Closed by afeld** 2021-05-24 15:22 UTC
Labels: g: final, i: SaaS, m: due date, t: days
