### ISSUE TITLE
Check in with BizOps about workload/scope for the new p-card holder

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#856] opened 2020-09-27 20:14 UTC
## Background information

During the 9/18 retro, it was discussed that the new p-card holder is taking on extra workload than previously thought. This might cause difficulty taking on the activities needed with the pcard needs that is expected to be transferred from the Tech Portfolio. 

## Acceptance criteria

- [x] The Tech Portfolio, Acquisition, and BizOps are on the same page about what p-card responsibilities will live where in the medium term

---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment] 2020-09-28 17:19
Possible duplicate of https://github.com/18F/tts-tech-portfolio/issues/680.

**Comment by melanienleopold** [comment] 2020-10-14 14:20
There is a meeting set up for 10/20 with supervisors and pcard holders.

**Comment by melanienleopold** [comment] 2020-10-15 16:46
Meeting set for 10/20 with OA, Biz Ops and Tech Portfolio.

**Comment by afeld** [comment] 2020-10-21 18:26
[Meeting notes](https://docs.google.com/document/d/1MG6Xp7HEBBwr1m2ENHvfBw7oBSF8uc1QqFvsRmQZAzY/edit)

**Comment by melanienleopold** [comment] 2020-10-27 13:08
Melanie is meeting with the new p-card holder on 10/28. Another meeting with all stakeholders is set for next week.

**Comment by afeld** [comment] 2020-11-03 17:25
P-card walkthrough set for 11/17.

- [ ] Look into having multiple Approving Officials per p-card holder in Pegasys

**Comment by melanienleopold** [comment] 2020-11-16 13:09
The way our sheet is set up currently is technically not compliant with pcard policy. According to Rochelle Pauling in the pcard office, each purchase card holder should only have on Approving Official. A backup can approve in the case that the AO is out of office. Right now, any software purchase has Aidan as the AO, no matter who purchases it. This approval gets uploaded from the sheet into Pegasys, so the AO in the sheet is the Pegasys AO. We may need to add another column to the micropurchase sheet for the internal AO and keep the official AO separate.

**Comment by melanienleopold** [comment] 2020-11-16 18:58
[644](https://github.com/18F/tts-tech-portfolio/issues/644) will continue the pcard transition.

**Closed by melanienleopold** 2020-11-16 18:58 UTC
Labels: g: accepted, i: acquisition, t: weeks
