### ISSUE TITLE
Documented way to handle ATO renewals - Due Date 10/1

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#744] opened 2020-08-17 20:40 UTC
## Background information

Follow up from: https://github.com/18F/tts-tech-portfolio/issues/658

https://docs.google.com/document/d/1NC736hj2JEUSorC-JnjUeCFj9b9WLvbibRRIlZYuIG0/edit?disco=AAAAJ9pailY

## Acceptance criteria

- [ ] It is clear who, what, where and when ATO renewals are handled

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment] 2020-10-05 17:23
Duplicate of https://github.com/18F/tts-tech-portfolio/issues/653.

**Closed by afeld** 2020-10-05 17:23 UTC
Labels: g: final, i: SaaS authorizations, m: due date, t: days
