### ISSUE TITLE
Federalist ATOs

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#838] opened 2020-09-21 16:33 UTC
## Acceptance criteria

- [definitive thing]
- [other definitive thing]

---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment] 2020-09-21 17:13
Duplicate of https://github.com/18F/tts-tech-portfolio/issues/833.

**Closed by afeld** 2020-09-21 17:13 UTC
Labels: g: initial
